#%RAML 0.8
title: HATEOAS Inc. Example API
version: v1
baseUri: http://hateoas-example.skqr.net/app_dev.php/api/{version}
mediaType: application/vnd.api+json
schemas:
  - some-resources: !include some-resources.schema.json
/some-resources:
  displayName: Some silly resource
  get:
    description: Retrieves resources.
    responses:
      200:
  /{some-resource-ids}:
    get:
      description: Retrieves one or more resources.
      responses:
        200:
    put:
      description: Updates one or more resources.
      responses:
        200:
        404:

