#%RAML 0.8
title: HATEOAS Inc. Example API
version: v1
baseUri: http://hateoas-example.skqr.net/app_dev.php/api/{version}
mediaType: application/vnd.api+json
schemas:
  - some-resources: !include some-resources.schema.json
/some-resources:
  displayName: Random resources
  post:
    description: Creates one or more random resources.
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/schema",
            "type": "object",
            "description": "A random resource.",
            "properties": {
              "some-resources": {
                "type": "object",
                "properties": {
                    "id":  { "type": "string" },
                    "content": { "type": "string" },
                    "links": {
                        "type": "object",
                        "properties": {
                            "author": { "type": "string" },
                            "comments": { "type": "array" }
                        },
                        "required": [ "author" ]
                    }
                },
                "required": [ "content" ]
            }
          }
    responses:
      201:
